### ISSUE TITLE
Project Not Working

### ISSUE THREAD

**Issue by dvizdos** [PurpleUSAMap/PurpleAmerica#16]
Hey guys, I think there is a problem with the project. Whenever I try to clone or download the project, it doesnt work. Also, @Sampendyal you didnt store the values as RGB, you just set them as red, green or white(not as RGB values though). As of right now, my local copy doesn't work and I can't integrate the formula without completely rewriting @Sampendyal code. I'll ask Mr. Neville about it during class today. Sorry I can't integrate the formula, but I will try to have **something** working by the end of today.

thanks guys and I'm sorry.

**Comment by LaurenSk8s** [comment]
Well shoot.  I can resend you the latest version of the USA map if you need it.
